[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/events"
  to = "/.netlify/functions/events"
  status = 200

[[redirects]]
  from = "/form"
  to = "/form.html"
  status = 200
